[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc"]

[phases.install]
cmds = ["python3.11 -m pip install -r requirements.txt"]

[start]
cmd = "python3.11 manage.py migrate --noinput && python3.11 manage.py createcachetable --verbosity 0 || true && python3.11 manage.py collectstatic --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT --timeout 120"
